# Generated by Django 5.2.4 on 2025-07-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
