# Generated by Django 5.2.4 on 2025-08-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
